using SiteKeeper.Shared.DTOs.API.Diagnostics; // For NodeDiagnosticsReport
using System;
using System.ComponentModel.DataAnnotations;

namespace SiteKeeper.Shared.DTOs.AgentHub
{
    /// <summary>
    /// DTO used by a Slave Agent to send a diagnostics report for its node to the Master.
    /// </summary>
    /// <remarks>
    /// This message is sent from an agent to the Master's AgentHub, typically after the agent
    /// has performed local diagnostic checks. It includes the agent's identifier, the timestamp
    /// of when the report was generated, and the detailed diagnostics report itself.
    /// Corresponds to the `AgentNodeDiagnosticsReport` schema in `web api swagger.yaml`,
    /// which wraps the standard <see cref="API.Diagnostics.NodeDiagnosticsReport"/>.
    /// </remarks>
    public class AgentNodeDiagnosticsReport
    {
        /// <summary>
        /// Unique identifier of the agent sending the diagnostics report, typically the node name.
        /// </summary>
        /// <example>"AppServer01"</example>
        [Required]
        public string AgentId { get; set; } = string.Empty;

        /// <summary>
        /// The detailed diagnostics report from the node.
        /// </summary>
        [Required]
        public NodeDiagnosticsReport Report { get; set; } = new NodeDiagnosticsReport();

        /// <summary>
        /// Timestamp (UTC) when this diagnostics report was generated by the agent.
        /// </summary>
        /// <example>"2023-10-27T12:15:00Z"</example>
        [Required]
        public DateTime Timestamp { get; set; }
    }
} 