using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SiteKeeper.Shared.DTOs.AgentHub
{
    /// <summary>
    /// DTO used by a Slave Agent to respond to a general command from the Master.
    /// </summary>
    /// <remarks>
    /// After executing a command received via <see cref="NodeGeneralCommandRequest"/>,
    /// the agent sends this message back to the Master's AgentHub. It includes the agent's ID,
    /// the type of the original command for correlation, a success/failure indicator,
    /// an optional payload with results (if successful), an optional error message (if failed),
    /// and a timestamp.
    /// Corresponds to the `AgentGeneralCommandResponse` schema in `web api swagger.yaml`.
    /// </remarks>
    public class AgentGeneralCommandResponse
    {
        /// <summary>
        /// Unique identifier of the agent sending the response, typically the node name.
        /// </summary>
        /// <example>"AppServer01"</example>
        [Required]
        public string AgentId { get; set; } = string.Empty;

        /// <summary>
        /// The type of the original command this response is for, used for correlation.
        /// This should match the <see cref="NodeGeneralCommandRequest.CommandType"/>.
        /// </summary>
        /// <example>"Ping" or "GetDetailedStatus"</example>
        [Required]
        public string OriginalCommandType { get; set; } = string.Empty;

        /// <summary>
        /// Indicates whether the command was executed successfully by the agent.
        /// </summary>
        /// <example>true</example>
        [Required]
        public bool IsSuccess { get; set; }

        /// <summary>
        /// Optional. A payload containing results or output data from the command if it was successful.
        /// The structure of this object depends on the <see cref="OriginalCommandType"/>.
        /// For example, a "GetDetailedStatus" command might return {"cpuUsage": 75, "memoryFreeMb": 1024}.
        /// </summary>
        public Dictionary<string, object>? ResponsePayload { get; set; }

        /// <summary>
        /// Optional. An error message if the command execution was not successful (<see cref="IsSuccess"/> is false).
        /// </summary>
        /// <example>"Component 'XYZ' not found for restart."</example>
        public string? ErrorMessage { get; set; }

        /// <summary>
        /// Timestamp (UTC) when this response was generated by the agent.
        /// </summary>
        /// <example>"2023-10-27T12:20:00Z"</example>
        [Required]
        public DateTime Timestamp { get; set; }
    }
} 