using System;
using System.ComponentModel.DataAnnotations;

namespace SiteKeeper.Shared.DTOs.MasterSlave
{
    /// <summary>
    /// DTO sent from Slave to Master to report its readiness for a specific task,
    /// in response to a PrepareForTaskInstruction.
    /// </summary>
    public class SlaveTaskReadinessReport
    {
        /// <summary>
        /// The unique identifier of the overall action this report pertains to.
        /// </summary>
        [Required]
        public string ActionId { get; set; } = string.Empty;

        /// <summary>
        /// The unique identifier of the specific task this readiness report is for.
        /// </summary>
        [Required]
        public string TaskId { get; set; } = string.Empty;

        /// <summary>
        /// The name of the slave agent sending this report.
        /// </summary>
        [Required]
        public string NodeName { get; set; } = string.Empty;

        /// <summary>
        /// Indicates whether the slave is ready to execute the task.
        /// </summary>
        [Required]
        public bool IsReady { get; set; }

        /// <summary>
        /// If <see cref="IsReady"/> is false, this field provides a human-readable reason.
        /// </summary>
        public string? ReasonIfNotReady { get; set; }

        /// <summary>
        /// Timestamp (UTC) when this readiness report was generated by the slave.
        /// </summary>
        [Required]
        public DateTime TimestampUtc { get; set; }
    }
} 