using System;
using System.ComponentModel.DataAnnotations;

namespace SiteKeeper.Shared.DTOs.MasterSlave
{
    /// <summary>
    /// DTO used by a Slave Agent to send heartbeat signals to the Master Agent.
    /// </summary>
    /// <remarks>
    /// Heartbeats are sent periodically to indicate that the slave is alive and responsive.
    /// They also provide a quick summary of the slave's current state, such as active task count.
    /// </remarks>
    public class SlaveHeartbeat
    {
        /// <summary>
        /// The unique name of the slave agent sending the heartbeat.
        /// </summary>
        /// <example>"SlaveNode-01"</example>
        [Required]
        public string NodeName { get; set; } = string.Empty;

        /// <summary>
        /// The UTC timestamp when the heartbeat was generated by the slave.
        /// </summary>
        [Required]
        public DateTimeOffset Timestamp { get; set; }

        /// <summary>
        /// The number of tasks currently active (being processed) on the slave agent.
        /// </summary>
        /// <example>2</example>
        [Range(0, int.MaxValue)]
        public int ActiveTasks { get; set; }

        /// <summary>
        /// The number of task execution slots currently available on the slave agent.
        /// This is typically MaxConcurrentTasks - ActiveTasks.
        /// </summary>
        /// <example>2</example>
        [Range(0, int.MaxValue)]
        public int AvailableTaskSlots { get; set; }

        /// <summary>
        /// Current CPU usage percentage (0-100).
        /// </summary>
        public double CpuUsagePercent { get; set; }

        /// <summary>
        /// Current RAM usage percentage (0-100).
        /// </summary>
        public double RamUsagePercent { get; set; }
    }
} 